#SITE CONFIGURATIONS
url: http://jcruiz.co
baseurl: "" # the subpath of your site, e.g. /blo

#THEME SPECIFIC CONFIGURATION
title: The Other Radio
description: Views of a Colombian on product management and the web
favicon:
author: Juan Camilo Ruiz

# Header and footer text
header_text: Colombian views on Product Management and more
header_feature_image: assets/img/header-feature.jpg
footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a>

description: "I'm Juan Camilo Ruiz, technologist and computer sciences professional from Bogotá, Colombia-living in Dublin. Product at Microsoft, former PM @BigCommerce, @Moovweb and @Oracle. Love technology, love to learn, welcome to my playground. This blog contains my personal opinions and don't represent anyone but me."
twitter_username: juanca
github_username:  jcruiz
linkedin_username: juancamiloruiz

# Build settings
#Original theme
# theme: minima
theme: type-on-strap
color_theme: auto
plugins:
  - jekyll-feed

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page
paginate: 5  # amount of posts to show per page
paginate_path: /page:num/

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png
# Format titles with titlecase?
titlecase: true

# Google Analytics
google_analytics_tracking_id: UA-44281567-1

#Well-known config
include:
  - .well-known/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
